### PR TITLE
[IN-253] Only valis from the current project are now pushed

### PR DESCRIPTION
**Pull request by franciscoatsantos**

### CODE REVIEW

**Review by antopemo — COMMENTED** [review]
LGTM

**Review by antopemo — APPROVED** [review]

**Review by cauenapier — CHANGES_REQUESTED** [review]
Can you add on the syummary popup, which Valis were not uploaded because they belong to another project or were not found.

So just on the If Not, add an extra message saying that the vali was not updated.

**Review by cauenapier — CHANGES_REQUESTED** [review]
I tested it only with Valis from the same project and I get the message bellow. 
image

I think that the for loop on line 371 need to have a check if failedDict is not zero

**Review by antopemo — APPROVED** [review]
LGTM

**Review by cauenapier — APPROVED** [review]
Awesome! LGTM

**Pull request merged**
